### PR TITLE
generate Typescript type declarations from sources and add them to the project

### PR DESCRIPTION
**Pull request by martinemmert**
- Typescript is added as an optional dependency
- run `npm run update-type-declarations` to update the type declarations.
- add a script to generate the type declarations from the JSDocs in the source files
- Typescript users can import the declarations in a project by referencing them in a `*.d.ts` file via `/// <reference types="..." />`

### CODE REVIEW

**Comment by KilledByAPixel** [comment]
Thanks for doing this, but I need to think on it. My goal with this engine is to keep things as simple as possible, and I don't even use typescript. Also It says that tsc is deprecated. Maybe it would make sense to have a branch or something? Right now I'm thinking I'd like to hold off on this until the engine gets more active use.

**Comment by altbdoor** [comment]
Sorry, just chiming in since I am interested in TypeScript stuff.

Looking in the TypeScript docs, it appears that one can generate the definitions directly in CLI:

```sh
# https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
npx -p typescript tsc src/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types

# or in the case of this project
npx -p typescript tsc ./engine/engine.all.js --declaration --allowJs --emitDeclarationOnly \
    --outFile @types/littlejsengine/index.d.ts
```

I believe this means that the definitions could be done in a separate branch (as proposed), perhaps as a nightly, CI/GitHub Actions job.

**Comment by openfinch** [comment]
Just wanted to chip in that this would be pretty useful. I understand that you might not use Typescript, but having the @types file bundled in makes it easier for developers that do.

**Comment by knopkem** [comment]
First of all, awesome project, I enjoy learning from it, thank you for providing this!
I would also be interested in having type declarations and I think this PR is a non intrusive way of providing them - in comparison to [porting everything to typescript](https://github.com/knopkem/LittleGameEngineTS).   
Regarding **tsc**, this is confusing I agree as [tsc ](https://www.npmjs.com/package/tsc) also exists as a deprecated package. However the correct way of using tsc is via the [typescript ](https://www.npmjs.com/package/typescript)package (this is the only thing you need and very active).
The proposal @altbdoor sounds good too, alternatively you could simple add the definitions to [definitelytyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Cheers

**Comment by KilledByAPixel** [comment]
Thank you for the input everyone. I've got it set up now to auto build index.d.ts whenever engine is rebuilt.

```call tsc engine.all.js --declaration --allowJs --emitDeclarationOnly --outFile index.d.ts```

https://github.com/KilledByAPixel/LittleJS/blob/main/engine/index.d.ts

Does that work for everyone?

**Comment by KilledByAPixel** [comment]
typescript is now fully supported and I added an example project!

https://killedbyapixel.github.io/LittleJS/examples/typescript/

**Comment by raylu** [comment]
I might have misconfigured `tsconfig.json`, but it seems like the current types don't work with ESM
```ts
import * as LittleJS from 'littlejsengine';
```
with `"strict": true` in `tsconfig.json`,
```
$ tsc
error TS7016: Could not find a declaration file for module 'littlejsengine'. '
[...]/node_modules/littlejsengine/build/littlejs.esm.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/littlejsengine` if it exists or add a new declaration (.d.ts) file containing `declare module 'littlejsengine';`

2 import * as LittleJS from 'littlejsengine';
```

**Pull request closed without merging**
