### PR TITLE
Load images from cross-origin domains

### PR DESCRIPTION
**Pull request by akira-cn**
Set `image.crossOrigiin='anonymous'` to enable images loading from cross domains.

### CODE REVIEW

**Comment by KilledByAPixel** [comment]
hey, thanks for looking at this but I think this would make more sense for a client to do rather then adding it to the core engine. what use case do you have where you need this?

**Comment by akira-cn** [comment]
I make the example game running on codepen. When I load the tileImage from CDN URL it cannot render as texture because it's cross origin.@KilledByAPixel

**Comment by KilledByAPixel** [comment]
can you fix it by adding tileImage.crossOrigin='anonymous' at the beginning of your code?

**Comment by akira-cn** [comment]
> can you fix it by adding tileImage.crossOrigin='anonymous' at the beginning of your code?

OK. It works for me. Thanks.

**Pull request closed without merging**
